name: Secondary test pipeline

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to print"
        required: true
        default: "hello world"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print input message
        run: echo "${{ github.event.inputs.message }}"
